version: "3.8"

services:
  vision-connect-angular:
    build:
      context: .  
      dockerfile: Dockerfile
    container_name: vision-connect-angular
    env_file:
      - .env  # Fichier .env dans le même répertoire
    networks:
      - internal
      - external
    ports:
      - "4200:4200"
    volumes:
      - .:/home/frontend/
    command: bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"

networks:
  internal:
    driver: bridge
  external:
    driver: bridge
